package util

const (
	MSG_USER_NOT_FOUND    = "Usuario no encontrado"
	MSG_USER_CREATED      = "Usuario creado correctamente"
	MSG_USER_UPDATED      = "Usuario actualizado correctamente"
	MSG_USER_DELETED      = "Usuario eliminado correctamente"
	MSG_EMAIL_DUPLICATE   = "El email ya esta registrado"
	MSG_INVALID_DATA      = "Los datos enviados no son validos"
	MSG_INVALID_ID        = "ID invalido"
	MSG_DNI_DUPLICATE     = "El DNI ya esta registrado"
	MSG_USER_LIST         = "Lista de usuarios"
	MSG_GET_OK            = "Usuario obtenido correctamente"
	MSG_CREATE_ERROR      = "Error al crear usuario"
	MSG_UPDATE_ERROR      = "Error al actualizar usuario"
	MSG_DELETE_ERROR      = "Error al eliminar usuario"
	MSG_LIST_ERROR        = "Error al listar usuarios"
	ERR_CODE_INVALID_BODY = "invalid_body"
	ERR_CODE_INVALID_ID   = "invalid_id"
	ERR_CODE_CREATE       = "create_error"
	ERR_CODE_UPDATE       = "update_error"
	ERR_CODE_DELETE       = "delete_error"
	ERR_CODE_LIST         = "list_error"
	ERR_CODE_NOT_FOUND    = "usuario_not_found"
	ERR_CODE_INVALID_PAGE = "invalid_pagination"
)
