package util

const (
	MSG_VENTA_CREATED                = "Venta registrada correctamente"
	MSG_VENTA_UPDATED                = "Venta actualizada correctamente"
	MSG_VENTA_DELETED                = "Venta eliminada correctamente"
	MSG_VENTA_LIST                   = "Lista de ventas"
	MSG_VENTA_GET                    = "Venta obtenida correctamente"
	MSG_VENTA_NOT_FOUND              = "Venta no encontrada"
	MSG_VENTA_CREATE_ERROR           = "Error al registrar venta"
	MSG_VENTA_UPDATE_ERROR           = "Error al actualizar venta"
	MSG_VENTA_DELETE_ERROR           = "Error al eliminar venta"
	MSG_VENTA_LIST_ERROR             = "Error al listar ventas"
	MSG_VENTA_VALIDATION_ERROR       = "Datos de venta invalidos"
	MSG_VENTA_TIPO_COMPROBANTE_ERROR = "Tipo de comprobante invalido. Use: 1=BOLETA, 2=FACTURA, 3=TICKET"
	MSG_VENTA_SERIE_ERROR            = "No se pudo determinar la serie del comprobante"
	MSG_VENTA_CORRELATIVO_ERROR      = "No se pudo obtener el correlativo automatico"
	MSG_VENTA_SUBTOTAL_REQUIRED      = "El subtotal debe ser mayor a cero"
	MSG_VENTA_USUARIO_REQUIRED       = "El usuario es obligatorio"
	MSG_VENTA_COMPROBANTE_REQUIRED   = "El tipo de comprobante es obligatorio"
	MSG_VENTA_QR_ERROR               = "Error al generar el codigo QR"
	MSG_VENTA_PAGINATION_INVALID     = "Parametros de paginacion invalidos"

	ERR_CODE_INVALID_BODY = "invalid_body"
	ERR_CODE_INVALID_ID   = "invalid_id"
	ERR_CODE_INVALID_PAGE = "invalid_pagination"
	ERR_CODE_CREATE       = "create_error"
	ERR_CODE_UPDATE       = "update_error"
	ERR_CODE_DELETE       = "delete_error"
	ERR_CODE_LIST         = "list_error"
	ERR_CODE_NOT_FOUND    = "not_found"
)
