-- =========================================================
-- SISTEMA DE VENTA DE PASAJES + LICENCIAS
-- MYSQL 8+
-- =========================================================

DROP DATABASE IF EXISTS SISTEMA_PASAJES;
CREATE DATABASE SISTEMA_PASAJES
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE SISTEMA_PASAJES;

-- =========================================================
-- 1. PROVEEDOR DEL SISTEMA (TU EMPRESA)
-- =========================================================
/*CREATE TABLE PROVEEDOR_SISTEMA (
    ID_PROVEEDOR     INT AUTO_INCREMENT PRIMARY KEY,
    RUC              CHAR(11) NOT NULL UNIQUE,
    RAZON_SOCIAL     VARCHAR(150) NOT NULL,
    NOMBRE_COMERCIAL VARCHAR(150),
    DIRECCION        VARCHAR(200),
    TELEFONO         VARCHAR(20),
    EMAIL            VARCHAR(100),
    WEB              VARCHAR(150)
) ENGINE = InnoDB;*/

-- =========================================================
-- 2. EMPRESA CLIENTE (EMPRESA DE TRANSPORTE)
-- =========================================================
/*CREATE TABLE EMPRESA (
    ID_EMPRESA       INT AUTO_INCREMENT PRIMARY KEY,
    RUC              CHAR(11) NOT NULL UNIQUE,
    RAZON_SOCIAL     VARCHAR(150) NOT NULL,
    NOMBRE_COMERCIAL VARCHAR(150),
    DIRECCION        VARCHAR(200),
    TELEFONO         CHAR(9) NOT NULL,
    EMAIL            VARCHAR(100),
    LOGO             VARCHAR(255),
    FECHA_CREACION   DATE NOT NULL,
    CREATED_AT       DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_EMPRESA_DELETED_AT (DELETED_AT)
) ENGINE = InnoDB;*/

-- =========================================================
-- 3. LICENCIA DEL SISTEMA
-- =========================================================
CREATE TABLE LICENCIA_SISTEMA (
    ID_LICENCIA      INT AUTO_INCREMENT PRIMARY KEY,
    CLAVE_LICENCIA   VARCHAR(100) UNIQUE,
    FECHA_ACTIVACION DATE NOT NULL,
    FECHA_EXPIRACION DATE NOT NULL,
    ESTADO           ENUM('OPERATIVO', 'SOLO_LECTURA', 'BLOQUEADO') NOT NULL DEFAULT 'OPERATIVO',
    FECHA_REGISTRO   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT       DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    CONSTRAINT CHK_LICENCIA_FECHAS
        CHECK (FECHA_EXPIRACION >= FECHA_ACTIVACION)
) ENGINE = InnoDB;

-- =========================================================
-- 4. TERMINALES
-- =========================================================
/*CREATE TABLE TERMINAL (
    ID_TERMINAL  INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE       VARCHAR(100) NOT NULL,
    CIUDAD       VARCHAR(100) NOT NULL,
    DEPARTAMENTO VARCHAR(100),
    DIRECCION    VARCHAR(200),
    ESTADO       ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
    CREATED_AT       DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT       DATETIME NULL,
    INDEX IDX_EMPRESA_DELETED_AT (DELETED_AT)
    UNIQUE KEY UQ_TERMINAL (NOMBRE, CIUDAD, DEPARTAMENTO)
) ENGINE = InnoDB;*/

-- =========================================================
-- 5. RUTAS
-- =========================================================
CREATE TABLE RUTA (
    ID_RUTA        INT AUTO_INCREMENT PRIMARY KEY,
    ID_ORIGEN_TERMINAL      INT NOT NULL,
    ID_DESTINO_TERMINAL     INT NOT NULL,
    DURACION_HORAS DECIMAL(5,2),
    CONSTRAINT FK_RUTA_ORIGEN_TERMINAL
        FOREIGN KEY (ID_ORIGEN_TERMINAL) REFERENCES TERMINAL (ID_TERMINAL),
    CONSTRAINT FK_RUTA_DESTINO_TERMINAL
        FOREIGN KEY (ID_DESTINO_TERMINAL) REFERENCES TERMINAL (ID_TERMINAL),
    CONSTRAINT CHK_RUTA_TERMINALES
        CHECK (ID_ORIGEN_TERMINAL <> ID_DESTINO_TERMINAL),
    CONSTRAINT CHK_RUTA_DURACION
        CHECK (DURACION_HORAS IS NULL OR DURACION_HORAS > 0),
    UNIQUE KEY UQ_RUTA_ORIGEN_DESTINO_TERMINAL (ID_ORIGEN_TERMINAL, ID_DESTINO_TERMINAL)
) ENGINE = InnoDB;

-- =========================================================
-- 6. TIPOS DE VEHICULO
-- =========================================================
CREATE TABLE TIPO_VEHICULO (
    ID_TIPO_VEHICULO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE           ENUM('CAMIONETA', 'AUTO', 'COMBI', 'MINI-BUS') NOT NULL,
    DESCRIPCION      VARCHAR(100)
) ENGINE = InnoDB;

-- =========================================================
-- 7. VEHICULOS
-- =========================================================
CREATE TABLE VEHICULO (
    ID_VEHICULO            INT AUTO_INCREMENT PRIMARY KEY,
    ID_TIPO_VEHICULO       INT NOT NULL,
    NRO_PLACA              VARCHAR(10) NOT NULL UNIQUE,
    MARCA                  VARCHAR(50),
    MODELO                 VARCHAR(50),
    ANIO_FABRICACION       YEAR,
    NUMERO_CHASIS          VARCHAR(50) UNIQUE,
    CAPACIDAD              INT NOT NULL,
    NRO_SOAT               VARCHAR(50),
    FECHA_VENC_SOAT        DATE,
    NRO_REVISION_TECNICA   VARCHAR(50),
    FECHA_VENC_REV_TECNICA DATE,
    ESTADO                 ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT FK_VEHICULO_TIPO
        FOREIGN KEY (ID_TIPO_VEHICULO) REFERENCES TIPO_VEHICULO (ID_TIPO_VEHICULO),
    CONSTRAINT CHK_VEHICULO_CAPACIDAD
        CHECK (CAPACIDAD > 0)
) ENGINE = InnoDB;

-- =========================================================
-- 8. ASIENTOS
-- =========================================================
CREATE TABLE ASIENTO (
    ID_ASIENTO     INT AUTO_INCREMENT PRIMARY KEY,
    ID_VEHICULO    INT NOT NULL,
    NUMERO_ASIENTO VARCHAR(3) NOT NULL,
    CONSTRAINT FK_ASIENTO_VEHICULO
        FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO (ID_VEHICULO),
    UNIQUE KEY UQ_ASIENTO_VEHICULO_NUMERO (ID_VEHICULO, NUMERO_ASIENTO)
) ENGINE = InnoDB;

-- NOTA: la disponibilidad del asiento por viaje se consulta via DETALLE_PASAJE
-- (si existe (ID_VIAJE, ID_ASIENTO) → ocupado, si no → disponible)

-- =========================================================
-- 9. CONDUCTORES
-- =========================================================
/*CREATE TABLE CONDUCTOR (
    ID_CONDUCTOR        INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRES             VARCHAR(100) NOT NULL,
    APELLIDOS           VARCHAR(100) NOT NULL,
    DNI                 CHAR(8) NOT NULL UNIQUE,
    TELEFONO            CHAR(9) NOT NULL,
    DIRECCION           VARCHAR(200),
    NUMERO_LICENCIA     VARCHAR(20) NOT NULL UNIQUE,
    CATEGORIA_LICENCIA  VARCHAR(10),
    FECHA_VENC_LICENCIA DATE NOT NULL,
    CREATED_AT       DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ESTADO              ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO'
) ENGINE = InnoDB;*/

-- =========================================================
-- 10. VIAJES
-- =========================================================
CREATE TABLE VIAJE (
    ID_VIAJE       INT AUTO_INCREMENT PRIMARY KEY,
    ID_RUTA        INT NOT NULL,
    ID_VEHICULO    INT NOT NULL,
    ID_CONDUCTOR   INT NOT NULL,
    FECHA_SALIDA   DATETIME NOT NULL,
    FECHA_LLEGADA  DATETIME,
    PRECIO_BASE    DECIMAL(10,2) NOT NULL,
    ESTADO         ENUM('PROGRAMADO', 'EN_CURSO', 'COMPLETADO', 'CANCELADO') NOT NULL DEFAULT 'PROGRAMADO',
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_VIAJE_RUTA
        FOREIGN KEY (ID_RUTA) REFERENCES RUTA (ID_RUTA),
    CONSTRAINT FK_VIAJE_VEHICULO
        FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO (ID_VEHICULO),
    CONSTRAINT FK_VIAJE_CONDUCTOR
        FOREIGN KEY (ID_CONDUCTOR) REFERENCES CONDUCTOR (ID_CONDUCTOR),
    CONSTRAINT CHK_VIAJE_PRECIO
        CHECK (PRECIO_BASE > 0),
    CONSTRAINT CHK_VIAJE_FECHAS
        CHECK (FECHA_LLEGADA IS NULL OR FECHA_LLEGADA >= FECHA_SALIDA)
) ENGINE = InnoDB;

-- =========================================================
-- 11. ROLES
-- =========================================================
/*CREATE TABLE ROL (
    ID_ROL      INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      ENUM('ADMIN', 'VENDEDOR','PROVEEDOR') NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(200),
    CREATED_AT       DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT       DATETIME NULL,
    INDEX IDX_EMPRESA_DELETED_AT (DELETED_AT)
) ENGINE = InnoDB;*/

-- =========================================================
-- 12. USUARIOS
-- =========================================================
CREATE TABLE USUARIO (
    ID_USUARIO     INT AUTO_INCREMENT PRIMARY KEY,
    ID_ROL         INT NOT NULL,
    NOMBRE         VARCHAR(100) NOT NULL,
    APELLIDOS      VARCHAR(100) NOT NULL,
    DNI            CHAR(8) NOT NULL UNIQUE,
    EMAIL          VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD       VARCHAR(255) NOT NULL,
    TELEFONO       VARCHAR(20),
    ESTADO         ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USUARIO_ROL
        FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
) ENGINE = InnoDB;

-- =========================================================
-- 13. PASAJEROS
-- =========================================================
/*CREATE TABLE PASAJERO (
    ID_PASAJERO      INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_DOCUMENTO   ENUM('DNI', 'CE', 'PASAPORTE', 'P.NAC.') NOT NULL DEFAULT 'DNI',
    NRO_DOCUMENTO    VARCHAR(15) NOT NULL UNIQUE,
    NOMBRES          VARCHAR(100) NOT NULL,
    APELLIDOS        VARCHAR(100) NOT NULL,
    TELEFONO         CHAR(9) NOT NULL,
    EMAIL            VARCHAR(100),
    FECHA_NACIMIENTO DATE,
    CREATED_AT       DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT       DATETIME NULL,
    INDEX IDX_TERMINAL_DELETED_AT (DELETED_AT)
) ENGINE = InnoDB;*/

-- =========================================================
-- 14. TIPO COMPROBANTE
-- =========================================================
/*CREATE TABLE TIPO_COMPROBANTE (
    ID_TIPO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE  ENUM('BOLETA', 'FACTURA', 'TICKET') NOT NULL UNIQUE
) ENGINE = InnoDB;*/

-- =========================================================
-- 15. VENTAS
-- =========================================================
CREATE TABLE VENTA (
    ID_VENTA            INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO          INT NOT NULL,
    ID_TIPO_COMPROBANTE INT NOT NULL,
    SERIE               VARCHAR(10) NOT NULL,
    CORRELATIVO         INT NOT NULL,
    FECHA_VENTA         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NOTA                VARCHAR(255),
    OBSERVACIONES       TEXT,
    QR_CODE             VARCHAR(255),
    SUBTOTAL            DECIMAL(10,2),
    IGV                 DECIMAL(10,2),
    TOTAL               DECIMAL(10,2) NOT NULL,
    ESTADO              ENUM('REGISTRADA', 'PAGADA', 'ANULADA') NOT NULL DEFAULT 'REGISTRADA',
    CONSTRAINT FK_VENTA_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT FK_VENTA_TIPO_COMPROBANTE
        FOREIGN KEY (ID_TIPO_COMPROBANTE) REFERENCES TIPO_COMPROBANTE (ID_TIPO),
    CONSTRAINT CHK_VENTA_SUBTOTAL
        CHECK (SUBTOTAL >= 0),
    CONSTRAINT CHK_VENTA_IGV
        CHECK (IGV >= 0),
    CONSTRAINT CHK_VENTA_TOTAL
        CHECK (TOTAL > 0),
    UNIQUE KEY UQ_VENTA_COMPROBANTE (ID_TIPO_COMPROBANTE, SERIE, CORRELATIVO)
) ENGINE = InnoDB;

-- =========================================================
-- 16. METODOS DE PAGO
-- =========================================================
/*CREATE TABLE METODO_PAGO (
    ID_METODO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE    ENUM('EFECTIVO', 'YAPE', 'PLIN', 'TARJETA', 'TRANSFERENCIA') NOT NULL UNIQUE
) ENGINE = InnoDB;*/

-- =========================================================
-- 17. PAGOS
-- =========================================================
CREATE TABLE PAGO (
    ID_PAGO    INT AUTO_INCREMENT PRIMARY KEY,
    ID_VENTA   INT NOT NULL,
    ID_METODO  INT NOT NULL,
    MONTO      DECIMAL(10,2) NOT NULL,
    FECHA_PAGO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PAGO_VENTA
        FOREIGN KEY (ID_VENTA) REFERENCES VENTA (ID_VENTA),
    CONSTRAINT FK_PAGO_METODO
        FOREIGN KEY (ID_METODO) REFERENCES METODO_PAGO (ID_METODO),
    CONSTRAINT CHK_PAGO_MONTO
        CHECK (MONTO > 0)
) ENGINE = InnoDB;

-- =========================================================
-- 18. DETALLE PASAJE
-- =========================================================
CREATE TABLE DETALLE_PASAJE (
    ID_DETALLE     INT AUTO_INCREMENT PRIMARY KEY,
    ID_VENTA       INT NOT NULL,
    ID_VIAJE       INT NOT NULL,
    ID_PASAJERO    INT NOT NULL,
    ID_ASIENTO     INT NOT NULL,
    PRECIO         DECIMAL(10,2) NOT NULL,
    DESCUENTO      DECIMAL(10,2),
    FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_DETALLE_VENTA
        FOREIGN KEY (ID_VENTA) REFERENCES VENTA (ID_VENTA),
    CONSTRAINT FK_DETALLE_VIAJE
        FOREIGN KEY (ID_VIAJE) REFERENCES VIAJE (ID_VIAJE),
    CONSTRAINT FK_DETALLE_PASAJERO
        FOREIGN KEY (ID_PASAJERO) REFERENCES PASAJERO (ID_PASAJERO),
    CONSTRAINT FK_DETALLE_ASIENTO
        FOREIGN KEY (ID_ASIENTO) REFERENCES ASIENTO (ID_ASIENTO),
    CONSTRAINT CHK_DETALLE_PRECIO
        CHECK (PRECIO > 0),
    CONSTRAINT CHK_DETALLE_DESCUENTO
        CHECK (DESCUENTO IS NULL OR (DESCUENTO >= 0 AND DESCUENTO <= PRECIO)),
    UNIQUE KEY UQ_VIAJE_ASIENTO (ID_VIAJE, ID_ASIENTO),
    UNIQUE KEY UQ_PASAJERO_VIAJE (ID_PASAJERO, ID_VIAJE)
) ENGINE = InnoDB;

-- =========================================================
-- 19. ENCOMIENDAS
-- =========================================================
CREATE TABLE ENCOMIENDA (
    ID_ENCOMIENDA       INT AUTO_INCREMENT PRIMARY KEY,
    ID_VENTA            INT NOT NULL,
    ID_VIAJE            INT NOT NULL,
    DESCRIPCION         VARCHAR(300),
    PESO_KG             DECIMAL(8,2),
    COSTO               DECIMAL(10,2) NOT NULL,
    REMITENTE_NOMBRE    VARCHAR(100) NOT NULL,
    REMITENTE_DOC       VARCHAR(20),
    DESTINATARIO_NOMBRE VARCHAR(100) NOT NULL,
    DESTINATARIO_DOC    VARCHAR(20),
    DESTINATARIO_TEL    VARCHAR(20),
    ESTADO              ENUM('PENDIENTE', 'EN_TRANSITO', 'ENTREGADO', 'DEVUELTO') NOT NULL DEFAULT 'PENDIENTE',
    FECHA_REGISTRO      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ENCOMIENDA_VENTA
        FOREIGN KEY (ID_VENTA) REFERENCES VENTA (ID_VENTA),
    CONSTRAINT FK_ENCOMIENDA_VIAJE
        FOREIGN KEY (ID_VIAJE) REFERENCES VIAJE (ID_VIAJE),
    CONSTRAINT CHK_ENCOMIENDA_PESO
        CHECK (PESO_KG IS NULL OR PESO_KG > 0),
    CONSTRAINT CHK_ENCOMIENDA_COSTO
        CHECK (COSTO > 0)
) ENGINE = InnoDB;


-- =========================================================
-- FIN DEL SCRIPT
-- =========================================================

ALTER TABLE PROVEEDOR_SISTEMA
    ADD COLUMN CREATED_AT DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN UPDATED_AT DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
